export const types = {
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOG_OUT: "LOG_OUT",

    REVIEW_LIST_LOADED: "REVIEW_LIST_LOADED",
    REVIEW_LIST_UPDATED: "REVIEW_LIST_UPDATED",
    REVIEW_LIST_ERROR: "REVIEW_LIST_ERROR",
    REVIEW_LIST_UPDATE: "REVIEW_LIST_UPDATE"
};