export const types = {
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOG_OUT: "LOG_OUT",

    REVIEW_LIST_LOADED: "REVIEW_LIST_LOADED",
    REVIEW_LIST_UPDATED: "REVIEW_LIST_UPDATED",
    REVIEW_LIST_ERROR: "REVIEW_LIST_ERROR",
    REVIEW_LIST_UPDATE: "REVIEW_LIST_UPDATE",

    PROFILE_DETAILS_LOADED: "PROFILE_DETAILS_LOADED",
    PROFILE_DETAILS_UPDATED: "PROFILE_DETAILS_UPDATED",
    PROFILE_DETAILS_ERROR: "PROFILE_DETAILS_ERROR",

    GENERAL_INFO_UPDATED: "GENERAL_INFO_UPDATED",

    SKILLS_LOAD: "SKILLS_LOAD",

    GOAL_UPDATE: "GOAL_UPDATE",
    GOAL_ADD: "GOAL_ADD",

    REVIEW_ADD: "REVIEW_ADD",
};